<a href="https://colab.research.google.com/github/v-yunusic/REPO-PYTHON-VY/blob/main/two-centuries-um/Notebook/ultramarathon.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PIP

In [2]:
pip install gdown

Requirement already satisfied: gdown in /usr/local/lib/python3.13/dist-packages (5.2.2)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.13/dist-packages (from gdown) (4.13.5)
Requirement already satisfied: filelock in /usr/local/lib/python3.13/dist-packages (from gdown) (4.2.1)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.13/dist-packages (from gdown) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.13/dist-packages (from gdown) (4.67.3)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4->gdown) (3.0.3)
Requirement already satisfied: typing-extensions>=4.0.0 in /usr/local/lib/python3.13/dist-packages (from beautifulsoup4->gdown) (4.16.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.13/dist-packages (from requests[socks]->gdown) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.13/dist-packages (from requests[socks]->gdown) (3.20)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.13/dist-packages (from requests[socks]->gdown) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.13/dist-packages (from requests[socks]->gdown) (2026.7.22)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.13/dist-packages (from requests[socks]->gdown) (1.7.1)

# LIBRERIAS

In [3]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as st
import sympy as sp
import pandas as pd
import seaborn as sns
import re # RegEx
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
import gdown
import gc

#========= KAGGLE =========#
import kagglehub

print('Librerias importadas!\n'+'-'*60)

Librerias importadas!
------------------------------------------------------------

# PREPROCESAMIENTO

In [4]:
countries = None

In [5]:
# https://drive.google.com/file/d/1z1JdNc9hZXbNxHaATZMrD_QcMR5qqMQG/view?usp=sharing

try:
  if not countries:
    file_id = '1z1JdNc9hZXbNxHaATZMrD_QcMR5qqMQG'
    url = f'https://drive.google.com/uc?id={file_id}'

    gdown.download(url, "UM_COUNTRIES.csv", quiet=True, use_cookies=False)

    countries = pd.read_csv('UM_COUNTRIES.csv', sep=',')
    print('\nDATAFRAME CARGADO!')
except:
  print(f'NO SE HA CARGADO DATAFRAME')

DATAFRAME CARGADO!

In [6]:
countries['Country'].unique()

array(['CHI', 'ARG', 'COL', 'RUS', 'SLO', 'HUN', 'GER', 'USA', 'CAN',
       'MEX', 'ITA', 'JPN', 'BLR', 'NED', 'BEL', 'FRA', 'GBR', 'CZE',
       'SRB', 'TPE', 'NZL', 'AUS', 'SGP', 'HKG', 'CHN', 'POL', 'LUX',
       'SUI', 'ROU', 'CRC', 'NGR', 'ESP', 'PAR', 'BRA', 'ISR', 'AUT',
       'SWE', 'UKR', 'SVK', 'MDA', 'UAE', 'DEN', 'THA', 'MAS', 'BUL',
       'GRE', 'ALB', 'SMR', 'PER', 'POR', 'CMR', 'IRL', 'LAT', 'ECU',
       'GUA', 'BRU', 'IND', 'INA', 'ALG', 'LIE', 'CRO', 'GUY', 'IRI',
       'PHI', 'URU', 'NOR', 'MAR', 'NCA', 'VIE', 'VEN', 'RSA', 'GAB',
       'TUR', 'LTU', 'FIN', 'TUN', 'QAT', 'CYP', 'ZIM', 'MOZ', 'LES',
       'MAW', 'BOT', 'NAM', 'SWZ', 'ZAM', 'MRI', 'KOR', 'CAM', 'SRI',
       'HON', 'BOL', 'PUR', 'GRL', 'UZB', 'BIH', 'MNE', 'MKD', 'MAC',
       'MDV', 'MGL', 'EST', 'JOR', 'UGA', 'NEP', 'EGY', 'KEN', 'JAM',
       'ESA', 'MLT', 'CAY', 'AND', 'DOM', 'HAI', 'ANG', 'KOS', 'ISL',
       'ETH', 'OMA', 'KAZ', 'AZE', 'FIJ', 'CHA', 'LBA', 'CPV', 'MAD',
       'MYA', 'AFG', 'LBN', 'PAN', 'CUB', 'TRI', 'ARM', 'BUR', 'PAK',
       'MON', 'IRE', 'CAF', 'SEN', 'TKM', 'IVB', 'SUD', 'ISV', 'CIV',
       'FRO', 'CGO', 'SOM', 'GAM', 'COD', 'TAN', 'BAN', 'KGZ', 'GIB',
       'KSA', 'BRN', 'RWA', 'BEN', 'IRQ', 'BHU', 'TWN', 'GEO', 'KUW',
       'SYR', 'NIG', 'BAH', 'TGA', 'MLI', 'ERI', 'TOG', 'COM', 'YEM',
       'COK', 'PNG', 'GUM', 'SAM', 'TJK', 'LAO', 'ARU', 'BIZ', 'MDG',
       'PLE', 'BER', 'BDI', 'PYF', 'GHA', 'BAR', 'LBR', 'STP', 'SKN',
       'SVE', 'DAN', 'NFI', 'MTN', 'GUI', 'ANT', 'GRN', 'SEY', 'GRB',
       'LCA', 'GBS', 'TKS', 'AHO', 'SLE', 'YUG', 'ACT'], dtype=object)

In [7]:
df = None

In [8]:
# PETICION DE DATA HACIA KAGGLE

try:
  path = kagglehub.dataset_download("aiaiaidavid/the-big-dataset-of-ultra-marathon-running")
  print('DATASET DE KAGGLE CARGADO!')
  print(path)
except Exception as e:
  print(f'Excepcion:\n{e}')

Downloading to /root/.cache/kagglehub/datasets/aiaiaidavid/the-big-dataset-of-ultra-marathon-running/2.archive...

100%|██████████| 246M/246M [00:01<00:00, 153MB/s]

Extracting files...

DATASET DE KAGGLE CARGADO!
/root/.cache/kagglehub/datasets/aiaiaidavid/the-big-dataset-of-ultra-marathon-running/versions/2

In [9]:
size = 0
width = 0
for c in pd.read_csv('/root/.cache/kagglehub/datasets/aiaiaidavid/the-big-dataset-of-ultra-marathon-running/versions/2/TWO_CENTURIES_OF_UM_RACES.csv',
                     chunksize=10000):
  if not c.empty:
    size += c.shape[0]
    width = c.shape[1]

print(f'Cantidad de filas:\n{size}')
print(f'Cantidad de columnas:\n{width}')

Cantidad de filas:
7461195
Cantidad de columnas:
13

##### ITERABLE

In [10]:
#pd.read_csv('/root/.cache/kagglehub/datasets/aiaiaidavid/the-big-dataset-of-ultra-marathon-running/versions/2/TWO_CENTURIES_OF_UM_RACES.csv',
                     #chunksize=10000):

##### SEPARAR POR PAÍS DE ATLETA

In [11]:
pais = 'CHI'.upper()

In [12]:
df = None

In [13]:
try:
  if not df:
    for c in pd.read_csv('/root/.cache/kagglehub/datasets/aiaiaidavid/the-big-dataset-of-ultra-marathon-running/versions/2/TWO_CENTURIES_OF_UM_RACES.csv',
                     chunksize=10000):
      filtrado = c[c['Athlete country'] == pais]
      if not c.empty:
        df = pd.concat([df, filtrado])
    print('\nDATAFRAME GENERADO!')
except:
  print('\nNO SE HA GENERADO DATAFRAME')

NO SE HA GENERADO DATAFRAME

In [14]:
df.head()

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
0,2018,06.01.2018,Selva Costera (CHI),50km,22,4:51:39 h,Tnfrc,CHI,1978.0,M,M35,10.286,0
1,2018,06.01.2018,Selva Costera (CHI),50km,22,5:15:45 h,Roberto Echeverría,CHI,1981.0,M,M35,9.501,1
2,2018,06.01.2018,Selva Costera (CHI),50km,22,5:16:44 h,Puro Trail Osorno,CHI,1987.0,M,M23,9.472,2
4,2018,06.01.2018,Selva Costera (CHI),50km,22,5:54:14 h,Baguales Trail,CHI,1992.0,M,M23,8.469,4
7,2018,06.01.2018,Selva Costera (CHI),50km,22,6:32:24 h,Reaktiva Chile,CHI,1967.0,F,W50,7.645,7

##### SEPARAR POR PAIS DE EVENTO

In [15]:
df = None

In [17]:
try:
  if not df or df.empty:
    for c in pd.read_csv('/root/.cache/kagglehub/datasets/aiaiaidavid/the-big-dataset-of-ultra-marathon-running/versions/2/TWO_CENTURIES_OF_UM_RACES.csv',
                     chunksize=10000):
      filtrado = c.loc[c['Event name'].str.find(pais) > -1]
      if not c.empty:
        df = pd.concat([df, filtrado])

    print('\nDATAFRAME GENERADO!')
except:
  print('\nNO SE HA GENERADO DATAFRAME')

NO SE HA GENERADO DATAFRAME

In [18]:
df['Event name'].unique()

array(['Selva Costera (CHI)', 'Futangue Challenge 62k - Cerro Mayo (CHI)',
       'Futangue Challenge 62k - Elite (CHI)', 'Pucón Trail Run (CHI)',
       'Corralco Challenge (CHI)',
       'Ultra Fiord Patagonia Chile 70 Kms (CHI)',
       'Ultra Fiord Patagonia Chile 100 Kms (CHI)',
       'Ultra Fiord Patagonia Chile 100 Millas (CHI)',
       'Ultra Fiord Patagonia Chile 50 Kms (CHI)',
       'Huilo Huilo Trail Run (CHI)', 'Putaendo Trail (CHI)',
       'Torrencial Valdivia Trail 80K (CHI)', 'Frontera Trail (CHI)',
       'La Gran Travesía (CHI)', 'Endurance Challenge Chile 50 Kms (CHI)',
       'Endurance Challenge Chile 80 Kms (CHI)',
       'Endurance Challenge Chile 160 Kms (CHI)',
       'Atacama Crossing (CHI)',
       'Ultra Trail Torres del Paine 50 Kms (CHI)',
       'Ultra Trail Torres del Paine 80 Kms (CHI)',
       'Navarino Trail (CHI)', 'El Cañi Trail 50KM Ultra (CHI)',
       'El Cañi Trail 80KM Ultra Sky (CHI)',
       'Gran Travesía de los Valles Ultra-Trail (CHI)',
       'Cochrane Patagonia Trail (CHI)', 'Antarctic 100k Race (CHI)',
       '70kms Ultramaraton Lican Ray - Villarrica (CHI)',
       'Ultra Trail Andes Infernal (CHI)',
       'Ultra Fiord Patagonia Chile 100km (CHI)',
       'Ultra Fiord Patagonia Chile 70km (CHI)',
       'Ultra Fiord Patagonia Chile 50km (CHI)',
       'Ultra Fiord Patagonia Chile 100mi (CHI)',
       'Trail Adventure Torres del Paine 50km (CHI)',
       'Trail Adventure Torres del Paine 90km (CHI)',
       'Torrencial Valdivia Trail 60K (CHI)',
       'Trail Running Putaendo 60 Kms (CHI)',
       'Trail Running Putaendo 100 Kms (CHI)',
       'Endurance Challenge Chile 160km (CHI)',
       'Vulcano Ultra Trail (VUT) - Ultra-73K (CHI)',
       'Vulcano Ultra Trail (VUT) - Ultraterra-100K (CHI)',
       '24 horas en pista Manquehue (CHI)',
       'Endurance Challenge Chile 50km (CHI)',
       'Endurance Challenge Chile 80km (CHI)',
       'Futangue Challenge 60k - Cerro Mayo (CHI)',
       'Ultra Fiord Patagonia Chile 50km - duo (CHI)',
       'Atacama Extreme 100 Miles (CHI)',
       'Torrencial Valdivia Trail 63K (CHI)',
       'Vulcano Ultra Trail (VUT) - Ultra-48K (CHI)',
       'Desafio a la Cruz Del Cabo Froward (CHI)',
       'Ultra Trail KoKamWaLa 60k (CHI)',
       'Pan American Race Walking Cup (CHI)', 'Tulahuen Ultra Run (CHI)',
       '24 horas en pista, Curico (CHI)',
       'Ultra Fiord Patagonia Chile 55 Kms (CHI)',
       'Atacama Crossing (Chile) (CHI)',
       'Ultramarathon Santiago-Vina del Mar (CHI)',
       '70 km Lican Ray-Villarrica (CHI)',
       'South American Race Walking Championships (CHI)',
       'Antarctic Ice Marathon Race (CHI)',
       'Copa Nacional de Marcha - Puerto Saavedra (CHI)',
       'Copa Nacional de Marcha - Los Angeles (CHI)',
       'Ultra Maraton de los Andes 80 Kms (CHI)',
       'Ultra Maraton de los Andes 50 Kms (CHI)',
       'Chilean Race Walking - Arica (CHI)',
       '100 Mile Polar Centenary Run (CHI)',
       'Rapa Nui GrandTrail 80 km (CHI)',
       'Vulcano Ultra Trail (VUT) (CHI)',
       'Patagonian Int. Marathon (CHI)',
       'Ultra Trail Torres del Paine 109km (CHI)',
       'Ultra Trail Torres del Paine 67km (CHI)',
       'Vulcano Ultra Trail (VUT) - Ultraterra-80K (CHI)',
       'Vulcano Ultra Trail (VUT) - Ultra-64K (CHI)',
       'Atacama Extreme 50 Miles (CHI)', 'Atacama Extreme 50 Km (CHI)',
       'NACAC Race Walking Championships (CHI)',
       'Pan American Race Walking Cup - Man (CHI)',
       'Pan American Race Walking Cup - Woman (CHI)',
       'Ultra Trail Torres del Paine 50km (CHI)',
       'Puerto Varas 100km (CHI)'], dtype=object)

In [19]:
df.columns.tolist()

['Year of event',
 'Event dates',
 'Event name',
 'Event distance/length',
 'Event number of finishers',
 'Athlete performance',
 'Athlete club',
 'Athlete country',
 'Athlete year of birth',
 'Athlete gender',
 'Athlete age category',
 'Athlete average speed',
 'Athlete ID']

In [20]:
print(f'Cantidad de filas:\n{df.shape[0]}')
print(f'Cantidad de columnas:\n{df.shape[1]}')

Cantidad de filas:
9792
Cantidad de columnas:
13

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9792 entries, 0 to 7076164
Data columns (total 13 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Year of event              9792 non-null   int64
 1   Event dates                9792 non-null   object
 2   Event name                 9792 non-null   object
 3   Event distance/length      9792 non-null   object
 4   Event number of finishers  9792 non-null   int64
 5   Athlete performance        9792 non-null   object
 6   Athlete club               1487 non-null   object
 7   Athlete country            9792 non-null   object
 8   Athlete year of birth      8946 non-null   float64
 9   Athlete gender             9792 non-null   object
 10  Athlete age category       8948 non-null   object
 11  Athlete average speed      9792 non-null   object
 12  Athlete ID                 9792 non-null   int64
dtypes: float64(1), int64(3), object(9)
memory usage: 1.0+ MB

In [22]:
# DEFINICION DE COLUMNAS NUMERICAS Y CATEGORICAS
col_categoricas = df.select_dtypes(include=['object']).columns.tolist()
col_numericas = df.select_dtypes(exclude=['object','bool']).columns.tolist()
col_bools = df.select_dtypes(include=['bool']).columns.tolist()

print(f'COLUMNAS NUMERICAS ({len(col_numericas)}):\n{col_numericas}\nCOLUMNAS CATEGORICAS ({len(col_categoricas)}):\n{col_categoricas}\nCOLUMNAS BOOLS ({len(col_bools)}):\n{col_bools}')

COLUMNAS NUMERICAS (4):
['Year of event', 'Event number of finishers', 'Athlete year of birth', 'Athlete ID']
COLUMNAS CATEGORICAS (9):
['Event dates', 'Event name', 'Event distance/length', 'Athlete performance', 'Athlete club', 'Athlete country', 'Athlete gender', 'Athlete age category', 'Athlete average speed']
COLUMNAS BOOLS (0):
[]

In [23]:
df[col_categoricas].describe()

,Event dates,Event name,Event distance/length,Athlete performance,Athlete club,Athlete country,Athlete gender,Athlete age category,Athlete average speed
count,9792,9792,9792,9792,1487,9792,9792,8948,9792.000
unique,146,79,38,8574,559,81,2,19,5800.000
top,17.10.2015,Atacama Crossing (CHI),50km,12:14:45 h,*Santiago,CHI,M,M23,5.648
freq,438,1451,2802,7,191,5501,8038,2753,10.000

In [24]:
df['Event dates'].unique()

array(['06.01.2018', '10.02.2018', '21.04.2018', '06.-07.04.2018',
       '05.-07.04.2018', '04.04.2018', '24.03.2018', '09.06.2018',
       '01.07.2018', '09.09.2018', '08.-09.09.2018', '20.10.2018',
       '19.-20.10.2018', '30.09.-06.10.2018', '22.09.2018', '15.12.2018',
       '09.12.2018', '10.11.2018', '03.11.2018', '13.02.2016',
       '24.-25.01.2016', '17.01.2016', '16.-17.01.2016', '15.-16.04.2016',
       '14.-16.04.2016', '19.03.2016', '26.06.2016', '11.06.2016',
       '15.-16.10.2016', '02.-09.10.2016', '25.09.2016', '10.12.2016',
       '12.-13.11.2016', '16.10.2016', '11.02.2017', '08.01.2017',
       '05.-08.04.2017', '25.03.2017', '19.-20.05.2017', '25.06.2017',
       '10.06.2017', '15.10.2017', '14.-15.10.2017', '01.-07.10.2017',
       '24.09.2017', '23.09.2017', '09.12.2017', '24.-25.11.2017',
       '09.02.2019', '03.02.2019', '20.01.2019', '05.01.2019',
       '27.04.2019', '21.04.2019', '30.06.2019', '15.06.2019',
       '28.09.2019', '08.09.2019', '07.-08.09.2019', '13.10.2019',
       '12.-13.10.2019', '29.09.-05.10.2019', '14.12.2019', '07.12.2019',
       '07.-08.12.2019', '16.11.2019', '19.01.2020', '04.01.2020',
       '17.-18.12.2021', '11.12.2021', '27.11.2021', '23.-24.10.2021',
       '05.02.2022', '25.09.-01.10.2022', '22.08.1998', '24.01.1998',
       '21.08.1999', '18.08.2001', '04.-10.07.2004', '03.04.2004',
       '15.01.2005', '21.01.2006', '08.01.2006', '15.12.2006',
       '23.-29.07.2006', '31.03.2007', '15.12.2007', '19.-25.08.2007',
       '30.03.-04.04.2008', '15.12.2008', '29.03.-03.04.2009',
       '21.03.2009', '10.01.2009', '12.12.2009', '17.10.2009',
       '07.-12.03.2010', '13.02.2010', '09.01.2010', '15.-17.12.2010',
       '23.10.2010', '06.-11.03.2011', '26.02.2011', '07.01.2011',
       '02.-04.12.2011', '30.10.2011', '08.01.2012', '04.-11.03.2012',
       '22.-24.11.2012', '10.-11.11.2012', '20.10.2012', '03.-10.03.2013',
       '06.01.2013', '13.12.2013', '07.12.2013', '20.-22.11.2013',
       '09.-10.11.2013', '19.10.2013', '28.09.2013', '05.01.2014',
       '07.06.2014', '27.09.2014', '26.09.2014', '20.12.2014',
       '06.12.2014', '20.11.2014', '08.-09.11.2014', '19.10.2014',
       '18.-19.10.2014', '05.-11.10.2014', '14.02.2015', '15.-16.01.2015',
       '04.01.2015', '16.-17.05.2015', '09.05.2015', '17.-18.04.2015',
       '16.-18.04.2015', '13.06.2015', '04.-11.10.2015', '03.10.2015',
       '26.09.2015', '05.12.2015', '07.-08.11.2015', '07.11.2015',
       '17.10.2015', '16.-17.10.2015', '07.02.1985'], dtype=object)

In [25]:
df['Event dates'] = df['Event dates'].apply(lambda x: x[-10:] if len(str(x)) > 10 else x)
df['Event dates'].head()

0    06.01.2018
1    06.01.2018
2    06.01.2018
3    06.01.2018
4    06.01.2018
Name: Event dates, dtype: object

In [26]:
df['Event dates'] = pd.to_datetime(df['Event dates'], dayfirst=True, errors='coerce')
df['Event dates'].loc[df['Event dates'].isna() == True].shape[0]

0

In [27]:
df.head()

,Year of event,Event dates,Event name,Event distance/length,Event number of finishers,Athlete performance,Athlete club,Athlete country,Athlete year of birth,Athlete gender,Athlete age category,Athlete average speed,Athlete ID
0,2018,2018-01-06,Selva Costera (CHI),50km,22,4:51:39 h,Tnfrc,CHI,1978.0,M,M35,10.286,0
1,2018,2018-01-06,Selva Costera (CHI),50km,22,5:15:45 h,Roberto Echeverría,CHI,1981.0,M,M35,9.501,1
2,2018,2018-01-06,Selva Costera (CHI),50km,22,5:16:44 h,Puro Trail Osorno,CHI,1987.0,M,M23,9.472,2
3,2018,2018-01-06,Selva Costera (CHI),50km,22,5:34:13 h,Columbia,ARG,1976.0,M,M40,8.976,3
4,2018,2018-01-06,Selva Costera (CHI),50km,22,5:54:14 h,Baguales Trail,CHI,1992.0,M,M23,8.469,4

In [28]:
df['Event dates'].unique()

<DatetimeArray>
['2018-01-06 00:00:00', '2018-02-10 00:00:00', '2018-04-21 00:00:00',
 '2018-04-07 00:00:00', '2018-04-04 00:00:00', '2018-03-24 00:00:00',
 '2018-06-09 00:00:00', '2018-07-01 00:00:00', '2018-09-09 00:00:00',
 '2018-10-20 00:00:00',
 ...
 '2015-04-18 00:00:00', '2015-06-13 00:00:00', '2015-10-11 00:00:00',
 '2015-10-03 00:00:00', '2015-09-26 00:00:00', '2015-12-05 00:00:00',
 '2015-11-08 00:00:00', '2015-11-07 00:00:00', '2015-10-17 00:00:00',
 '1985-02-07 00:00:00']
Length: 134, dtype: datetime64[ns]

In [29]:
df['Athlete age'] = df['Year of event'] - df['Athlete year of birth']

In [30]:
# APLICAR SIEMPRE Y CUANDO CANTIDAD DE VALORES NULOS SEA < 5% DEL DATAFRAME
df = df.loc[(df['Athlete year of birth'].isna() == False) & (df['Athlete age category'].isna() == False)]

In [31]:
df = df.drop(columns=['Athlete club',
                      'Year of event',
                      'Athlete year of birth',
                      'Athlete age category'])

In [32]:
df['Event distance/length'].loc[df['Event distance/length'].str.find('km') <= -1].unique()

array(['24h', '100mi', '50mi'], dtype=object)

In [33]:
def millas_a_km(x):
    if isinstance(x, str) and 'mi' in x:
        miles = float(re.search(r'\d+\.?\d*', x).group())
        if miles > 0:
            km = round(miles * 1.60934)
            return f"{km}km"
    return x

df['Event distance/length'] = df['Event distance/length'].apply(millas_a_km)

In [34]:
df['Event distance/length'].unique()

array(['50km', '62km', '70km', '81km', '46km', '80km', '100km', '160km',
       '250km/6Etappen', '51.5km', '52km', '84.5km', '45km', '51km',
       '90km', '61km', '47km', '141km', '63km', '64km', '105km', '50.7km',
       '73km', '24h', '58km', '161km', '49.2km', '48km', '60km', '55km',
       '50.3km', '98.2km', '133km', '109km', '67km', '113km', '173km'],
      dtype=object)

In [35]:
df[['Athlete performance','Athlete average speed']].loc[df['Athlete performance'].str.find('h') <= -1]

        Athlete performance Athlete average speed
1160507          207.950 km                 8.665
1160508          200.650 km                  8.36
1160509          191.240 km                 7.968
1160510          179.050 km                  7.46
1160511          170.700 km                 7.113
...                     ...                   ...
6773318          105.950 km                 4.415
6773319          102.600 km                 4.275
6773321          100.650 km                 4.194
6773322           90.500 km                 3.771
6773323           90.350 km                 3.765

[93 rows x 2 columns]

In [36]:
# ASISTIDO CON IA
def km_a_hr(x, y):
  if isinstance(x, str) and not 'h' in x:
    num = float(re.search(r'\d+\.?\d*', x).group())
    n = float(y)
    if n > 0:
      time = num/n
      hr = int(time)
      m = int((time - hr) * 60)
      s = int(round(((time - hr) * 60 - m) * 60))
      return f'{hr}:{m}:{s} h'
  return x

df['Athlete performance'] = df.apply(lambda row: km_a_hr(row['Athlete performance'], row['Athlete average speed']), axis=1)

In [37]:
df.columns.tolist()

['Event dates',
 'Event name',
 'Event distance/length',
 'Event number of finishers',
 'Athlete performance',
 'Athlete country',
 'Athlete gender',
 'Athlete average speed',
 'Athlete ID',
 'Athlete age']

In [38]:
df = df[[
 'Athlete ID',
 'Athlete country',
 'Athlete age',
 'Athlete gender',
 'Athlete performance',
 'Athlete average speed',
 'Event dates',
 'Event name',
 'Event distance/length',
 'Event number of finishers']]

In [39]:
df.duplicated().sum()

np.int64(0)

In [40]:
nulos = pd.DataFrame({
    "nulos": df.isna().sum(),
    "pct": df.isna().mean() * 100,
}).sort_values("pct", ascending=False)

nulos

                           nulos  pct
Athlete ID                     0  0.0
Athlete country                0  0.0
Athlete age                    0  0.0
Athlete gender                 0  0.0
Athlete performance            0  0.0
Athlete average speed          0  0.0
Event dates                    0  0.0
Event name                     0  0.0
Event distance/length          0  0.0
Event number of finishers      0  0.0

In [41]:
df.head()

,Athlete ID,Athlete country,Athlete age,Athlete gender,Athlete performance,Athlete average speed,Event dates,Event name,Event distance/length,Event number of finishers
0,0,CHI,40.0,M,4:51:39 h,10.286,2018-01-06,Selva Costera (CHI),50km,22
1,1,CHI,37.0,M,5:15:45 h,9.501,2018-01-06,Selva Costera (CHI),50km,22
2,2,CHI,31.0,M,5:16:44 h,9.472,2018-01-06,Selva Costera (CHI),50km,22
3,3,ARG,42.0,M,5:34:13 h,8.976,2018-01-06,Selva Costera (CHI),50km,22
4,4,CHI,26.0,M,5:54:14 h,8.469,2018-01-06,Selva Costera (CHI),50km,22

In [47]:
first_year = df['Event dates'].dt.year.min()
last_year = df['Event dates'].dt.year.max()

In [48]:
first_year, last_year

(1998, 2022)

In [ ]:
df['year'], df['month'] = df['date'].dt.year, df['date'].dt.month

In [49]:
df.to_csv(f'ULTRAMARATONES_{pais}_({first_year}-{last_year}).csv', index=False)